import { hashValue } from './encryptionService.js';

/**
 * In-memory consent log store.
 * In production, replace with a persistent, append-only database.
 */
const consentLogs = new Map();

/**
 * Log a consent record before recording starts.
 * @param {object} params
 * @param {string} params.sessionId - Session identifier
 * @param {string} params.doctorId - Doctor/user identifier
 * @param {string} params.ipAddress - Client IP (will be hashed)
 * @param {string} [params.patientRef] - Optional patient reference (anonymized)
 * @returns {object} The consent record
 */
export const logConsent = ({ sessionId, doctorId, ipAddress, patientRef }) => {
    const consentRecord = {
        consentId: `CONSENT-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
        sessionId,
        doctorId: doctorId || 'DOCTOR_001', // Default for single-user mode
        ipHash: hashValue(ipAddress || 'unknown'),
        patientRef: patientRef || 'ANONYMOUS',
        consentConfirmed: true,
        consentTimestamp: new Date().toISOString(),
        consentVersion: '1.0',
        consentText: 'I confirm that patient consent has been obtained for this clinical session recording. The patient has been informed that: (1) the session will be recorded, (2) AI will process the audio for documentation, (3) audio is deleted after processing by default, and (4) they may request data deletion at any time.',
    };

    // Store indexed by sessionId for quick lookup
    consentLogs.set(sessionId, consentRecord);

    console.log(`📝 Consent logged for session: ${sessionId}`);
    return consentRecord;
};

/**
 * Get consent record for a session.
 */
export const getConsent = (sessionId) => {
    return consentLogs.get(sessionId) || null;
};

/**
 * Check if consent exists for a session.
 */
export const hasConsent = (sessionId) => {
    return consentLogs.has(sessionId);
};

/**
 * Get all consent logs (for admin/audit).
 */
export const getAllConsents = () => {
    return Array.from(consentLogs.values());
};

/**
 * Export consent log for a specific session as a downloadable object.
 */
export const exportConsentLog = (sessionId) => {
    const consent = consentLogs.get(sessionId);
    if (!consent) return null;

    return {
        ...consent,
        exportedAt: new Date().toISOString(),
        exportFormat: 'JSON',
        legalNotice: 'This consent record is generated by CeriNote Clinical Documentation System. It serves as proof of patient consent for the associated clinical session recording and AI-assisted documentation.',
    };
};
